{"timestamp":"2025-07-01T02:52:10.162216","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-01T02:52:10.162608","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/dag_go_k8s.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-01T02:52:11.521551Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-01T02:52:11.522116Z","level":"info","event":" Previous state of the Task instance: queued","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-01T02:52:11.522259Z","level":"info","event":"Current task name:run_go_app_local_config","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-01T02:52:11.522374Z","level":"info","event":"Dag name:go_app_k8s_demo","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-01T02:52:11.327938","level":"info","event":"Building pod go-app-local-config-9y7tl152 with labels: {'dag_id': 'go_app_k8s_demo', 'task_id': 'run_go_app_local_config', 'run_id': 'manual__2025-07-01T025201.9211170000-709fd8cd5', 'kubernetes_pod_operator': 'True', 'try_number': '1'}","logger":"airflow.task.operators.airflow.providers.cncf.kubernetes.operators.pod.KubernetesPodOperator"}
{"timestamp":"2025-07-01T02:52:11.330026","level":"info","event":"Secrets backends loaded for worker","count":1,"backend_classes":["EnvironmentVariablesBackend"],"logger":"supervisor"}
{"timestamp":"2025-07-01T02:52:11.602387","level":"warning","event":"Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'host.docker.internal'. (_ssl.c:1010)\"))': /api/v1/namespaces/default/pods?labelSelector=dag_id%3Dgo_app_k8s_demo%2Ckubernetes_pod_operator%3DTrue%2Crun_id%3Dmanual__2025-07-01T025201.9211170000-709fd8cd5%2Ctask_id%3Drun_go_app_local_config%2Calready_checked%21%3DTrue%2C%21airflow-worker","logger":"urllib3.connectionpool"}
{"timestamp":"2025-07-01T02:52:11.611163","level":"warning","event":"Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'host.docker.internal'. (_ssl.c:1010)\"))': /api/v1/namespaces/default/pods?labelSelector=dag_id%3Dgo_app_k8s_demo%2Ckubernetes_pod_operator%3DTrue%2Crun_id%3Dmanual__2025-07-01T025201.9211170000-709fd8cd5%2Ctask_id%3Drun_go_app_local_config%2Calready_checked%21%3DTrue%2C%21airflow-worker","logger":"urllib3.connectionpool"}
{"timestamp":"2025-07-01T02:52:11.618835","level":"warning","event":"Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'host.docker.internal'. (_ssl.c:1010)\"))': /api/v1/namespaces/default/pods?labelSelector=dag_id%3Dgo_app_k8s_demo%2Ckubernetes_pod_operator%3DTrue%2Crun_id%3Dmanual__2025-07-01T025201.9211170000-709fd8cd5%2Ctask_id%3Drun_go_app_local_config%2Calready_checked%21%3DTrue%2C%21airflow-worker","logger":"urllib3.connectionpool"}
{"timestamp":"2025-07-01T02:52:11.627550Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-01T02:52:11.629515Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-01T02:52:11.629823Z","level":"info","event":"Task:<Task(KubernetesPodOperator): run_go_app_local_config>","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-01T02:52:11.630118Z","level":"info","event":"Failure caused by HTTPSConnectionPool(host='host.docker.internal', port=55300): Max retries exceeded with url: /api/v1/namespaces/default/pods?labelSelector=dag_id%3Dgo_app_k8s_demo%2Ckubernetes_pod_operator%3DTrue%2Crun_id%3Dmanual__2025-07-01T025201.9211170000-709fd8cd5%2Ctask_id%3Drun_go_app_local_config%2Calready_checked%21%3DTrue%2C%21airflow-worker (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'host.docker.internal'. (_ssl.c:1010)\")))","chan":"stdout","logger":"task"}
{"timestamp":"2025-07-01T02:52:11.626351","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"MaxRetryError","exc_value":"HTTPSConnectionPool(host='host.docker.internal', port=55300): Max retries exceeded with url: /api/v1/namespaces/default/pods?labelSelector=dag_id%3Dgo_app_k8s_demo%2Ckubernetes_pod_operator%3DTrue%2Crun_id%3Dmanual__2025-07-01T025201.9211170000-709fd8cd5%2Ctask_id%3Drun_go_app_local_config%2Calready_checked%21%3DTrue%2C%21airflow-worker (Caused by SSLError(SSLCertVerificationError(1, \"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'host.docker.internal'. (_ssl.c:1010)\")))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":825,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1088,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py","lineno":599,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py","lineno":617,"name":"execute_sync"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py","lineno":566,"name":"get_or_create_pod"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/cncf/kubernetes/operators/pod.py","lineno":539,"name":"find_pod"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api/core_v1_api.py","lineno":15823,"name":"list_namespaced_pod"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api/core_v1_api.py","lineno":15942,"name":"list_namespaced_pod_with_http_info"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api_client.py","lineno":348,"name":"call_api"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api_client.py","lineno":180,"name":"__call_api"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/api_client.py","lineno":373,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/rest.py","lineno":244,"name":"GET"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/kubernetes/client/rest.py","lineno":217,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py","lineno":135,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py","lineno":182,"name":"request_encode_url"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/poolmanager.py","lineno":443,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":871,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":871,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":871,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}]},{"exc_type":"SSLError","exc_value":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'host.docker.internal'. (_ssl.c:1010)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":488,"name":"_make_request"}]},{"exc_type":"SSLCertVerificationError","exc_value":"[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'host.docker.internal'. (_ssl.c:1010)","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":464,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":1093,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":741,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":920,"name":"_ssl_wrap_socket_and_match_hostname"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py","lineno":480,"name":"ssl_wrap_socket"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/ssl_.py","lineno":524,"name":"_ssl_wrap_socket_impl"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":455,"name":"wrap_socket"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":1041,"name":"_create"},{"filename":"/usr/local/lib/python3.12/ssl.py","lineno":1319,"name":"do_handshake"}]}]}
